<a href="https://colab.research.google.com/github/NazHub1993/ML_Notebooks/blob/main/Heart_Disease_Dataset(HW_of_Codebasics).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import pandas as pd
import numpy as np
df=pd.read_csv('heart.csv')
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [67]:
df.shape

(918, 12)

In [68]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [69]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

#Remove outliers using z-score

In [70]:
numeric_cols=df.select_dtypes(include=['number']).columns

In [71]:
print(numeric_cols)

Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak',
       'HeartDisease'],
      dtype='object')

In [72]:
text_cols=df.select_dtypes(include=['object']).columns

In [73]:
print(text_cols)

Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object')

#Filtering out rows where z-score>3

In [74]:
from scipy import stats
df=df[np.abs(stats.zscore(df[numeric_cols])<3).all(axis=1)]

In [75]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [76]:
from sklearn.preprocessing import LabelEncoder,StandardScaler
df=pd.get_dummies(df,drop_first=True)
df.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,True,True,False,False,True,False,False,False,True
1,49,160,180,0,156,1.0,1,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,0,True,True,False,False,False,True,False,False,True
3,48,138,214,0,108,1.5,1,False,False,False,False,True,False,True,True,False
4,54,150,195,0,122,0.0,0,True,False,True,False,True,False,False,False,True

In [77]:
df.shape

(902, 16)

In [78]:
df.columns

Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak',
       'HeartDisease', 'Sex_M', 'ChestPainType_ATA', 'ChestPainType_NAP',
       'ChestPainType_TA', 'RestingECG_Normal', 'RestingECG_ST',
       'ExerciseAngina_Y', 'ST_Slope_Flat', 'ST_Slope_Up'],
      dtype='object')

In [79]:
x=df.drop('HeartDisease',axis=1)
y=df.HeartDisease

In [80]:
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)

In [81]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.25,random_state=42)

In [82]:
from sklearn import svm
model=svm.SVC(C=1,gamma=0.1,kernel='rbf')
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.8628318584070797

In [83]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'C': [0.1, 1, 10],
    'gamma': ['scale', 0.1, 0.01],
    'kernel': ['rbf', 'linear']
}
grid=GridSearchCV(svm.SVC(),param_grid,cv=5)
grid.fit(x_scaled,y)
print(grid.best_params_)

{'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}

In [85]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(svm.SVC(),x,y,cv=5)
scores.mean()

np.float64(0.6895273173726213)

In [86]:
from sklearn.ensemble import BaggingClassifier
bagged_model=BaggingClassifier(
    estimator=svm.SVC(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True
)
bagged_model.fit(x_train,y_train)
bagged_model.score(x_test,y_test)

0.8628318584070797

In [88]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.7876106194690266

In [89]:
from sklearn.ensemble import BaggingClassifier
bagged_model=BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True
)
bagged_model.fit(x_train,y_train)
bagged_model.score(x_test,y_test)

0.8451327433628318

#Using bagging in case of DecisionTreeClassifier improves score greatly